### PR TITLE
Metaprogramming Ruby

### PR DESCRIPTION
**Pull request by tranvictor**
Metaprogramming Ruby takes you go deep into Ruby magic of metaprogramming. After reading 50% of the book, you will have a strong knowledge of how Ruby works, how things are possible with Ruby. In contrast, you can even explain things that you thought it is obvious but it's not, really. You would never be the same once you read this book. (Level: Intermediate, Advanced)

### CODE REVIEW

**Comment by runlevel5** [comment]
:+1:

**Comment by huydx** [comment]
@tranvictor em them ti comment ve noi dung cuon sach, tai sao no can nhe :dancer:

**Comment by tranvictor** [comment]
@huydx e thêm comment vào book list luôn a nhé?

**Comment by huydx** [comment]
@tranvictor ok em

**Comment by runlevel5** [comment]
@tranvictor can you please rebase? it's good to go

**Comment by tranvictor** [comment]
@joneslee85 I just fixed the conflict, is it good enough?

**Pull request merged**
